#!/usr/bin/env bash
# Description: 
#   This Script get/update lastest uTLGBotLib depending libraries from lastest
#

echo ""
echo " Trying to get/update uTLGBotLib depending libraries from lastest."
echo ""

echo " Downloading multihttpsclient repository..."
rm -rf multihttpsclient
git clone --recurse-submodules https://github.com/J-Rios/multihttpsclient
if [[ $? != 0 ]]; then
    echo "   Error: Can't clone multihttpsclient library."
    echo ""
    exit 1
fi

echo " Downloading jsmn repository..."
rm -rf jsmn
git clone --recurse-submodules https://github.com/zserge/jsmn
if [[ $? != 0 ]]; then
    echo "   Error: Can't clone jsmn library."
    echo ""
    exit 1
fi
cd jsmn
git checkout 18e9fe42cbfe21d65076f5c77ae2be379ad1270f
cd ..

echo ""
echo " Process completed."

exit 0
